apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-portfolio

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - qdrant.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-engineer-portfolio
  app.kubernetes.io/managed-by: kustomize
